### ISSUE TITLE
buildspec.yaml

### ISSUE THREAD

**Issue by jlpl1999** [ttulka/aws-samples#2]
I am following your github repo to build out the cross account for pipeline. Would you please share the buildspec.yaml. Basically, I like to see the aws cloudformation output the template into s3 artifact,.Thanks for your sharing repo to public

**Comment by ttulka** [comment]
The buildspec.yaml really doesn't belong to this templates because it's project-specific and the pipeline is independent on what happens in CodeBuild.

For example, if your project is in Node.js your buildspec-test.yml could look as follows:
```
version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
```
